// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function handleClick(_, _$1) {
  console.log("clicked!");
  return /* () */0;
}

var component = ReasonReact.reducerComponent("Page");

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var send = param[/* send */4];
      return React.createElement("div", undefined, String(param[/* state */2][/* count */0]), React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(send, /* Increment */0);
                        })
                    }, "Increment"), React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(send, /* Decrement */1);
                        })
                    }, "Decrement"));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* count */0];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action !== 0) {
        return /* Update */Block.__(0, [/* record */[/* count */state[/* count */0] - 1 | 0]]);
      } else {
        return /* Update */Block.__(0, [/* record */[/* count */state[/* count */0] + 1 | 0]]);
      }
    });
  return newrecord;
}

exports.handleClick = handleClick;
exports.component = component;
exports.make = make;
/* component Not a pure module */
